### ISSUE TITLE
[change] Remove unneeded code and anything related to it

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netengine#53]
The first version of this library was a nice experiment, which was never really used.

What we know right now is that we need to add support for SNMP to OpenWISP, so we should focus on this goal and forget anything else.
The SSH and HTTP backends, even though are nice, are not extremely needed and I doubt we'll be able to maintain something which we do not need and not really use.

For this reason, I believe we should remove anything that is not SNMP related:

- SSH code and docs
- HTTP code and docs
- `resources/manufacturers.py`, if we need this functionality we can use the `netaddr` library, but first we have to ensure we need it

We can still leave a mention in the documentation that the first iterations of this library contained backends for SSH and HTTP, we could leave links to the old versions, explaining that implementing something like that is possible.

**Comment by nemesisdesign** [comment]
@purhan please double check and ensure everything unneded is removed, eg: https://github.com/openwisp/netengine/tree/master/netengine/resources (we can use `netaddr` to do that as we already do in openwisp-monitoring, look in that repo to find out).

**Comment by nemesisdesign** [comment]
Here as well: https://github.com/openwisp/netengine/tree/master/netengine/utils
Probably all of those are not needed anymore, please double check and let us know what you can find.

**Comment by pandafy** [comment]
https://github.com/openwisp/netengine/blob/365875d2662315899fe4b7671fe22a400e8d2e45/netengine/backends/snmp/openwrt.py#L366-L375


These methods are implemented in `BaseBackend`, removing these should have no side effect. 
https://github.com/openwisp/netengine/blob/365875d2662315899fe4b7671fe22a400e8d2e45/netengine/backends/snmp/base.py#L36-L42

**Comment by purhan** [comment]
Closed in #59
