### ISSUE TITLE
[deps] Bind dependency versions

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netengine#58]
Let's bind the dependency versions to avoid issues in the future.

I suggest also to get rid of `requirements.txt` and use `setup_requires` directly in `setup.py` which is simpler.

**Comment by purhan** [comment]
This is a duplicate of https://github.com/openwisp/netengine/issues/55

**Comment by pandafy** [comment]
> Let's bind the dependency versions to avoid issues in the future.
> 
> I suggest also to get rid of `requirements.txt` and use `setup_requires` directly in `setup.py` which is simpler.
